export const queryKeys = {
  exercises: ['exercises'] as const,
  templates: ['templates'] as const,
  workoutSummaries: ['workoutSummaries'] as const,
  weeklyWorkoutSummaries: ['weeklyWorkoutSummaries'] as const,
  records: ['records'] as const,
  exerciseHistories: ['exerciseHistory'] as const,
  exerciseHistory: (exerciseId: string) => ['exerciseHistory', exerciseId] as const,
  runs: ['runs'] as const,
  runsTotal: ['runsTotal'] as const,
  run: (runId: string) => ['run', runId] as const,
  weighIns: ['weighIns'] as const,
  activitySteps: ['activitySteps'] as const,
  dailySteps: (days: number) => ['activitySteps', 'daily', days] as const,
  hourlySteps: (days: number) => ['activitySteps', 'hourly', days] as const,
  runWindowSteps: (runsKey: string) => ['activitySteps', 'runWindows', runsKey] as const,
  healthAuthStatus: ['healthAuthStatus'] as const,
  dailyMacros: (date: string) => ['dailyMacros', date] as const,
  macrosHistory: ['macrosHistory'] as const,
  foods: ['foods'] as const,
  foodSearch: (query: string) => ['foods', query] as const,
  brandedFoodSearch: (query: string) => ['brandedFoodSearch', query] as const,
  userAvatar: ['userAvatar'] as const,
  aiUsage: ['aiUsage'] as const,
  coachState: ['coachState'] as const,
  dailyMacrosAll: ['dailyMacros'] as const
}

export const mutationKeys = {
  completeWorkout: ['completeWorkout'] as const,
  createExercise: ['createExercise'] as const,
  deleteExercise: ['deleteExercise'] as const,
  createTemplate: ['createTemplate'] as const,
  deleteTemplate: ['deleteTemplate'] as const,
  completeRun: ['completeRun'] as const,
  discardRun: ['discardRun'] as const,
  syncOfflineRuns: ['syncOfflineRuns'] as const,
  logWeighIn: ['logWeighIn'] as const,
  deleteWeighIn: ['deleteWeighIn'] as const,
  requestHealthPermissions: ['requestHealthPermissions'] as const,
  logMealEntry: ['logMealEntry'] as const,
  updateMealEntry: ['updateMealEntry'] as const,
  deleteMealEntry: ['deleteMealEntry'] as const,
  estimateMacros: ['estimateMacros'] as const,
  scanNutritionLabel: ['scanNutritionLabel'] as const,
  createFood: ['createFood'] as const,
  deleteFood: ['deleteFood'] as const,
  updateAvatar: ['updateAvatar'] as const,
  syncProfile: ['syncProfile'] as const,
  updateMacroTargets: ['updateMacroTargets'] as const,
  enrollCoach: ['enrollCoach'] as const,
  updateCoachSettings: ['updateCoachSettings'] as const,
  deleteCoach: ['deleteCoach'] as const,
  ackCheckIn: ['ackCheckIn'] as const
}
