export default {
    RootAuth: 'RootAuth',
    MEALS: 'Meals',
    WORKOUTS: 'Workouts',
    ADD_FOOD: 'Add Food',
    CREATE_FOOD: 'Create Food',
    PREVIOUS_DAILY_MEAL_ENTRIES: 'Previous Daily Meal Entries',
    FOOD_DETAIL_SCREEN: 'Food Detail',
    ADD_EXERCISE: 'Add Exercise',
    CREATE_EXERCISE: 'Create Exercise',
    PREVIOUS_DAILY_EXERCISE_ENTRIES: 'Previous Daily Exercise Entries',
    ACCOUNT: 'Account',
    REGISTER: 'Register',
    LOG_IN: 'Log In',
    WORKOUT_TEMPLATE_DETAIL: 'Workout Template',
    DEBUG: 'Debug',
    CREATE_TEMPLATE: 'Create Template',
    SEARCH_EXERCISES: 'Search Exercises',
} as const;

