export default {
  RootAuth: 'RootAuth',
  MACROS: 'Macros',
  WORKOUTS: 'Workouts',
  ADD_FOOD: 'Add Food',
  CREATE_FOOD: 'Create Food',
  FOOD_DETAIL_SCREEN: 'Food Detail',
  LOG_WITH_AI: 'Log with AI',
  MACROS_HISTORY: 'Macros History',
  ADD_EXERCISE: 'Add Exercise',
  CREATE_EXERCISE: 'Create Exercise',
  PREVIOUS_DAILY_EXERCISE_ENTRIES: 'Previous Daily Exercise Entries',
  ACCOUNT: 'Account',
  RUNS: 'Runs',
  RUN_FLOW: 'Run Flow',
  RUN_SUMMARY: 'Run Summary',
  PROGRESS: 'Progress',
  SELECT_EXERCISE: 'Select Exercise',
  LOG_WEIGHT: 'Log Weight',
  REGISTER: 'Register',
  LOG_IN: 'Log In',
  FORGOT_PASSWORD: 'Forgot Password',
  CREATE_TEMPLATE: 'Create Template',
  COACH_INTRO: 'Coach Intro',
  COACH_SETUP: 'Coach Setup',
  COACH_PROFILE: 'Coach Profile',
  COACH_REVEAL: 'Coach Reveal',
  COACH_SETTINGS: 'Coach Settings'
} as const
