export default {
  RootAuth: 'RootAuth',
  MACROS: 'Macros',
  WORKOUTS: 'Workouts',
  ADD_FOOD: 'Add Food',
  CREATE_FOOD: 'Create Food',
  FOOD_DETAIL_SCREEN: 'Food Detail',
  LOG_WITH_AI: 'Log with AI',
  MACROS_HISTORY: 'Macros History',
  ADD_EXERCISE: 'Add Exercise',
  CREATE_EXERCISE: 'Create Exercise',
  PREVIOUS_DAILY_EXERCISE_ENTRIES: 'Previous Daily Exercise Entries',
  ACCOUNT: 'Account',
  RUNS: 'Runs',
  RUN_FLOW: 'Run Flow',
  RUN_SUMMARY: 'Run Summary',
  PROGRESS: 'Progress',
  SELECT_EXERCISE: 'Select Exercise',
  LOG_WEIGHT: 'Log Weight',
  REGISTER: 'Register',
  LOG_IN: 'Log In',
  FORGOT_PASSWORD: 'Forgot Password',
  CREATE_TEMPLATE: 'Create Template',
  MEAL_PLAN_INTRO: 'Meal Plan Intro',
  MEAL_PLAN_GOAL: 'Meal Plan Goal',
  MEAL_PLAN_ABOUT_YOU: 'Meal Plan About You',
  MEAL_PLAN_ACTIVITY: 'Meal Plan Activity',
  MEAL_PLAN_DIET: 'Meal Plan Diet',
  MEAL_PLAN_FOOD_PREFERENCES: 'Meal Plan Food Preferences',
  MEAL_PLAN_FOOD_SEARCH: 'Meal Plan Food Search',
  MEAL_PLAN_SCHEDULE: 'Meal Plan Schedule',
  MEAL_PLAN_COOKING_BUDGET: 'Meal Plan Cooking Budget',
  MEAL_PLAN_TARGETS: 'Meal Plan Targets',
  MEAL_PLAN_EDIT_TARGETS: 'Meal Plan Edit Targets',
  MEAL_PLAN_GENERATING: 'Meal Plan Generating',
  RECIPE_DETAIL: 'Recipe Detail',
  SWAP_MEAL: 'Swap Meal',
  SWAP_PREVIEW: 'Swap Preview',
  GROCERY_LIST: 'Grocery List',
  LOG_PLANNED_MEAL: 'Log Planned Meal',
  PLAN_SETTINGS: 'Plan Settings'
} as const
